steps:
  - name: gcr.io/k8s-skaffold/pack
    entrypoint: pack
    args:
      - 'build'
      - '--builder=paketobuildpacks/builder:base'
      - '--publish'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'

  - name: ghcr.io/jamesward/easycloudrun
    entrypoint: deploy
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'BUILD_ID=$BUILD_ID'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'IMAGE_NAME=$REPO_NAME'
      - 'IMAGE_VERSION=$COMMIT_SHA'
      - 'REGION=us-central1'
      - 'DEPLOY_OPTS=--execution-environment=gen2'
